- doc/item_file.rst
- src/bundlewrap/items/files.py
> [WIP] add verify_cmds for file items

- src/bundlewrap/utils/ui.py
As discussed recently.
We assume that `stty size` is too slow to be run on each update. Thus, we directly issue an `ioctl()` call instead of forking/execing.
> Use ioctl() to detect terminal width and refresh on each update

- bundlewrap/operations.py
I rewrote that function to not use any Event or custom pipes. It should
have worked but it didn't. Well, it mostly worked. Sometimes it didn't.
I then finally discovered that OpenSSH's master process (when using
multiplexing) inherits some pipes and never closes them -- which breaks
everything I had in mind.
Your original idea (using a busy loop and Event) is just the right thing
to do. It's a complex topic, though. Proof reading would be advisable.
> Comment on what's going on in operations.run()

- bundlewrap/cmdline/parser.py
Undocumented, but see #212. %)
> "-p" and "-P" can be pre-configured using environment variables

- bundlewrap/utils/ui.py
PR for #222.
Won't work on Windows or other non-UNIX-like systems, but neither will `term_width()` and maybe a bunch of other stuff.
> Drain any pending input on stdin before asking questions

- bundlewrap/cmdline/parser.py
- bundlewrap/cmdline/plot.py
> Plot groups

- bundlewrap/cmdline/__init__.py
- bundlewrap/exceptions.py
- bundlewrap/repo.py
- docs/content/repo/requirements.txt.md
- docs/mkdocs.yml
> Requirements check

- bundlewrap/cmdline/test.py
- bundlewrap/group.py
- bundlewrap/metadata.py
- bundlewrap/node.py
- tests/bw_test.py
somewhat involved, just merge it if you don't have time to review
> Metadata checks

- bundlewrap/operations.py
> fix compatibility with fish

- bundlewrap/cmdline/apply.py
- bundlewrap/cmdline/run.py
- bundlewrap/cmdline/test.py
- bundlewrap/cmdline/verify.py
- bundlewrap/concurrency.py
- bundlewrap/exceptions.py
- bundlewrap/node.py
- bundlewrap/utils/ui.py
> quit faster

- bundlewrap/cmdline/lock.py
- bundlewrap/cmdline/parser.py
- bundlewrap/cmdline/run.py
- bundlewrap/exceptions.py
- bundlewrap/items/__init__.py
- bundlewrap/items/actions.py
- bundlewrap/lock.py
- bundlewrap/node.py
- bundlewrap/utils/time.py
- docs/content/guide/env.md
- docs/content/guide/locks.md
- docs/content/misc/about.md
- docs/content/misc/faq.md
- docs/mkdocs.yml
- tests/utils_time.py
PR for #191 
The existing lock is now called a "hard lock" because it continues to prevent concurrent apply operations on the node, regardless of which user it is. These new locks are "soft locks" because they are ignored by the users who created them.
As of now, the management UI for the soft locks is in place. TODO:
> Soft locks

- AUTHORS
- bundlewrap/items/directories.py
- bundlewrap/items/files.py
- bundlewrap/items/pkg_openbsd.py
- bundlewrap/items/svc_rcd.py
- bundlewrap/items/users.py
- docs/content/items/pkg_openbsd.md
- docs/content/items/svc_rcd.md
- docs/content/repo/bundles.md
- docs/content/repo/nodes.py.md
This pull request introduces support for OpenBSD.
Todo:
> [WIP] OpenBSD compatibility

- bundlewrap/cmdline/__init__.py
- tests/bw_nodes.py
- tests/bw_repo.py
> invoke bw from repo subdirs

- bundlewrap/cmdline/hash.py
- bundlewrap/cmdline/parser.py
- bundlewrap/group.py
- bundlewrap/node.py
- bundlewrap/repo.py
- bundlewrap/utils/statedict.py
- tests/bw_hash.py
- tox.ini
> Metadata hashing

- bundlewrap/cmdline/nodes.py
- bundlewrap/cmdline/parser.py
- bundlewrap/cmdline/run.py
- bundlewrap/group.py
- bundlewrap/node.py
- bundlewrap/utils/remote.py
- bundlewrap/utils/testing.py
- docs/content/repo/groups.py.md
- docs/content/repo/nodes.py.md
- tests/bw_nodes.py
> node.dummy

- bundlewrap/lock.py
- docs/content/guide/env.md
> [WIP] add BW_HARDLOCK_EXPIRY

- AUTHORS
- bundlewrap/items/pkg_dnf.py
- bundlewrap/items/pkg_yum.py
- docs/content/items/pkg_dnf.md
- docs/content/repo/bundles.md
- docs/mkdocs.yml
clone pkg_yum to support dnf, the next generation yum
> add dnf support

- bundlewrap/group.py
- bundlewrap/node.py
- bundlewrap/repo.py
- docs/content/repo/groups.py.md
- tests/integration/bw_nodes.py
> add group.members_add and .members_remove

- bundlewrap/operations.py
> tag debug output with command ID

- bundlewrap/cmdline/__init__.py
- bundlewrap/concurrency.py
- bundlewrap/utils/ui.py
- docs/content/guide/env.md
> add `BW_DEBUG_LOG_DIR`

- bundlewrap/items/pkg_pacman.py
I'm not too happy with that `tarball` stuff. It feels like a hack. Maybe we should remove this in bw 3.0 and advise people to set up their own package repos.
> Update pkg_pacman for recently addded package cache

- bundlewrap/cmdline/__init__.py
- bundlewrap/cmdline/parser.py
- docs/content/guide/env.md
@vain I'm not sure if we need both, but I can't really settle for just one or the other...
> add `BW_REPO_PATH` and `bw —repository`

- bundlewrap/cmdline/test.py
> Warn about unused bundles

- bundlewrap/items/pkg.py
- bundlewrap/items/pkg_apt.py
- bundlewrap/items/pkg_dnf.py
- bundlewrap/items/pkg_pacman.py
- bundlewrap/items/pkg_yum.py
It appears this was a *global* cache, covering all nodes. Whoops.
> Cache packages per-node and cache full IDs

- bundlewrap/items/__init__.py
- bundlewrap/items/pkg_apt.py
- docs/content/items/pkg_apt.md
> when_creating item attribute

- bundlewrap/cmdline/lock.py
> Exclude dummy nodes from `bw lock`

- bundlewrap/items/pkg_snap.py
- docs/content/items/pkg_snap.md
- docs/content/repo/bundles.md
- docs/mkdocs.yml
> Feature snap support

- docs/content/repo/nodes.py.md
I have started to enhance the docs. This is still a work in progress. Feel free to comment while I'm working on it.
> [WIP] documentation enhancements regarding #286 

- bundlewrap/cmdline/parser.py
- bundlewrap/cmdline/test.py
- bundlewrap/node.py
- bundlewrap/utils/cmdline.py
- tests/integration/bw_test.py
> rework `bw test`

- CHANGELOG.md
- bundlewrap/cmdline/plot.py
- bundlewrap/cmdline/test.py
- bundlewrap/deps.py
- bundlewrap/itemqueue.py
- bundlewrap/items/__init__.py
- bundlewrap/items/groups.py
- bundlewrap/items/pkg.py
- bundlewrap/items/pkg_apt.py
- bundlewrap/items/pkg_dnf.py
- bundlewrap/items/pkg_openbsd.py
- bundlewrap/items/pkg_pacman.py
- bundlewrap/items/pkg_pip.py
- bundlewrap/items/pkg_snap.py
- bundlewrap/items/pkg_yum.py
- bundlewrap/items/pkg_zypper.py
- bundlewrap/items/users.py
- bundlewrap/node.py
- docs/content/guide/dev_item.md
- docs/content/guide/migrate_23.md
> change `Item.BLOCK_CONCURRENT` into a class method

- bundlewrap/utils/remote.py
- added sha256 sum to PATH_INFO.
> added sha256

- bundlewrap/items/pkg_openbsd.py
- tests/unit/pkg_openbsd.py
> Fix openbsd package issues

- bundlewrap/cmdline/verify.py
- bundlewrap/node.py
- bundlewrap/utils/text.py
> handle exceptions during bw verify as unknown items

- bundlewrap/items/kubernetes.py
- docs/content/items/k8s.md
This PR adds support for
- ClusterRole
- ClusterRoleBinding
- ServiceAccount
> Add RBAC K8S items

- bundlewrap/group.py
- bundlewrap/lock.py
- docs/content/guide/locks.md
Solve the problem of unlockable nodes: Hardware, k8s, ...
I'll write docs once we agree that this is the way to go.
Lock format and location changes (would make #448 obsolete). If we need
this sooner than 4.0, we'd have to implement a backwards-compatible
fallback.
> Flexilocks: Put locks on other nodes

- bundlewrap/cmdline/diff.py
- bundlewrap/cmdline/parser.py
Note that --prompt can be mixed with those.
> bw diff: external commands

- docs/content/items/k8s.md
> docs: Bump k8s apiVersions

- CHANGELOG.md
- bundlewrap/cmdline/metadata.py
- bundlewrap/cmdline/parser.py
- bundlewrap/utils/dicts.py
- bundlewrap/utils/text.py
- bundlewrap/utils/ui.py
- tests/integration/bw_metadata.py
closes #496 
Should colors be on by default?
> add `bw metadata --colors` and `--hide-defaults`

- bundlewrap/bundle.py
Closes #454.
Backwards-compatible, could be in a hypothetical 3.11.
> Make an empty dict available in items.py for all known items

- bundlewrap/items/svc_openbsd.py
> svc_openbsd: Must not run concurrently

- bundlewrap/items/kubernetes.py
This reverts commit a05b24b5edbbe5a10ed03c1005edb324f8bdc631.
This was wrong. You must have matching apiVersions. You just cannot
patch an existing object when apiVersions differ, because object schemas
(can) change between apiVersions.
> Revert "k8s: Ignore 'apiVersion' when comparing state"

- bundlewrap/cmdline/metadata.py
- bundlewrap/cmdline/test.py
- bundlewrap/metagen.py
- bundlewrap/repo.py
- docs/content/guide/env.md
- tests/integration/bw_hash.py
- tests/integration/bw_test.py
TODO:
* docs
* tests
* automated cleanup
* disable for `bw test -M`
> Metadata caching

- bundlewrap/cmdline/diff.py
target_nodes[0] is not a valid operation for a set.
> bw diff: Fix type error

- bundlewrap/items/groups.py
As is the case with users, groups are managed by pw(8), and
groups cannot be managed concurrently.
IMO this also cleans up the `fix()` method a little bit.
> Group: Fix module on FreeBSD installs

- bundlewrap/items/users.py
This allows using Faults in salts.
> Force salt to text before password hashing

- bundlewrap/cmdline/apply.py
- bundlewrap/cmdline/diff.py
- bundlewrap/cmdline/parser.py
- bundlewrap/cmdline/verify.py
- bundlewrap/exceptions.py
- bundlewrap/items/__init__.py
- bundlewrap/items/actions.py
- bundlewrap/items/directories.py
- bundlewrap/items/files.py
- bundlewrap/items/kubernetes.py
- bundlewrap/items/symlinks.py
- bundlewrap/items/users.py
- bundlewrap/node.py
- bundlewrap/utils/dicts.py
- docs/content/guide/dev_item.md
- tests/integration/bw_apply_files.py
> show item details when creating and deleting

- bundlewrap/deps.py
- bundlewrap/items/__init__.py
- bundlewrap/utils/plot.py
- docs/content/repo/items.py.md
- tests/integration/bw_apply_beforeafter.py
> add `before` and `after` item attributes

- docs/content/guide/quickstart.md
Just to make it a little bit clearer on what to do exactly to get going quicker.
> add localhost SSH verification steps

- bundlewrap/items/kubernetes.py
Without specifying the apiVersion, k8s chooses *some* version that it
sees fit. If this doesn't match our version in the repo, items will
never be fixable. k8s' choice changes on k8s updates.
Closes #618.
> k8s: Use apiVersion when retrieving objects

- AUTHORS
Is "add me to the bottom of the list" correct? The list doesn't seem to be sorted in any way.
> add me to AUTHORS

- bundlewrap/items/files.py
(Needs more testing, will do tomorrow.)
> Files: GNU chmod needs special treatment

- bundlewrap/items/files.py
- docs/content/items/file.md
- tests/integration/bw_test.py
Same as `verify_with`, but called when running `bw test`.
> items/file: add test_with

- bundlewrap/items/files.py
- docs/content/items/file.md
```
✘ rx300  gitea  file:/usr/local/bin/gitea  
│ 
│ content_hash
│   548018e2c9c1dfd9ac0919aec743759027ad9c72
│ → da39a3ee5e6b4b0d3255bfef95601890afd80709
│ source
│   <missing>
│ → https://dl.gitea.io/gitea/1.15.2/gitea-1.15.2-linux-amd64
╵
```
> items/files: add content_type 'download'

- bundlewrap/bundle.py
`<bundlewrap.bundle.Bundle object at 0x1125f6e20>` -> `<Bundle: systemd>`
> print bundle name: add __repr__

- bundlewrap/items/__init__.py
> Fix unless + faults

- bundlewrap/items/dconf.py
Somehow, this never occured to me while testing ...
> items/dconf: fix integers

- bundlewrap/items/svc_openbsd.py
The first commit being the more important one. The speedup is considerable.
> svc_openbsd tuning

- bundlewrap/repo.py
- bundlewrap/secrets.py
There are several occasions where bw appears to "hang" because it just shows an empty status line. Let's try to tell the users what's going on.
TODO:
> More "with io.job()" to avoid awkward silence

- bundlewrap/deps.py
Cache results of resolve_selector().
This can't be easily done in a generic way with a decorator, because "items" is a list and not hashable. Besides, the cache would lose its effect if "originating_item_id" would be taken into account: I'm seeing lots of queries to, say, "bundle:foo", but all of them have a different "originating_item_id". So, it's better to just resolve "bundle:foo", cache the result, and then remove the offending item afterwareds.
(This shaves off another ~7 seconds from the “processing dependencies” stage of our Icinga node.)
> deps: Optimize _prepare_deps()

- bundlewrap/exceptions.py
- bundlewrap/lock.py
- bundlewrap/node.py
- bundlewrap/operations.py
- docs/content/guide/api.md
> Handle cases where children are terminated by signals + introduce TransportException

- bundlewrap/items/pkg_pacman.py
@Kunsi Please give this a shot regarding #688.
> pkg pacman fixes

- bundlewrap/operations.py
-   Stop using preexec_fn when launching processes. This has the biggest
impact. Use process_group=0 instead to get the same result. (For
some reason that I have not investigated, setting preexec_fn -- even
if it is just an empty function -- has a massive impact on
performance.)
-   Get rid of the threads. We use select() anyway, so we can just do
that in the main thread.
> Optimize run_local() in operations.py

- bundlewrap/operations.py
This was racy and didn't show up immediately.
Bringing "elif" back is important, because we must read all available data before we mark the fd for closing.
> Fix poll() on GNU

- bundlewrap/items/symlinks.py
Fixing the target essentially creates a new symlink, so we must also fix ownership afterwards.
(This should hardly have any effect in practice, since [symlink ownership isn’t very relevant on most systems](https://superuser.com/a/1188707), except macOS. Still, if someone happened to set ownership on symlinks, bw broke, i.e. you had to do two runs of `bw apply`, because the first one didn’t fix everything.)
> Fix fixing symlink targets

- bundlewrap/utils/ui.py
I haven’t really tried a lot of different terminals but this affects VTE and that library is used in quite a lot of stuff.
Before:
https://github.com/bundlewrap/bundlewrap/assets/82671/ef34eae7-909b-4592-a36d-7b86e3038586
After:
https://github.com/bundlewrap/bundlewrap/assets/82671/9431e4ca-fa59-4ce0-bed3-a2433a03a73f
I hope the comments in the code explain everything.
> Avoid most of the flickering in some terminals

- bundlewrap/items/routeros.py
this fixes issues where one attibute is not valid without the other being set, ie it is not allowed to add a port as untagged to a vlan as long as it is still tagged member of the same vlan. this change also speeds up the overall apply because fewer requests have to be made.
> items/routeros: update all attributes of an item at once

- bundlewrap/items/svc_openrc.py
This allows registering services to e.g. the "boot" runlevel instead of
forcing "default"
Signed-off-by: Robert Günzler <r@gnzler.io>
> Add runlevel support to svc_openrc

- bundlewrap/items/pkg_apt.py
This fixes #584.
Without marking a package as explicitely installed, a package might come in as a dependency of another package without bundlewrap noticing it. This would allow a mechanism such as `apt autoremove` to remove the package, even though we explicitely want this package to be installed, leading to possible downtime.
For this to work, i had to override some methods imported from the generic `Pkg` class, which seems fine to me.
```
➤ bw items carlene pkg_apt:weechat
{
"installed": true,
"mark": "manual"
}
➤ bw items carlene pkg_apt:weechat --state
{
"installed": true,
"mark": "manual"
}
```
Has been tested on a couple of systems of my own, and of course i had some packages installed as dependencies.
> items/pkg_apt: mark packages as 'explicitely installed'

- bundlewrap/items/routeros.py
- docs/content/items/routeros.md
this works the same way that directories work.
> items/routeros: purge unused subitems

- bundlewrap/items/pkg_apt.py
This should fix the concerns stated in https://github.com/bundlewrap/bundlewrap/pull/764 about being a performance regression.
> Rework "apt manually installed"

- bundlewrap/cmdline/apply.py
- bundlewrap/cmdline/parser.py
- bundlewrap/node.py
Fixes #455.
Could you give this a spin, @fkusei?
> Add "bw apply --no-skipped-items"

- bundlewrap/utils/ui.py
See individual commit messages.
> ui: Restore original signal handlers, prevent double-activation

- bundlewrap/cmdline/debug.py
This PR adds tab completion to the bw debug REPL
> `bw debug` add tab completion to REPL

- bundlewrap/cmdline/lock.py
- bundlewrap/lock.py
CC #752.
Not sure about the warning message that comes before the table:
> Warn on "bw lock add" if already locked

- bundlewrap/cmdline/items.py
- bundlewrap/cmdline/parser.py
> add `bw items --blame`

- bundlewrap/utils/ui.py
> utils.ui.IOManager(): support being used as a context manager

- bundlewrap/cmdline/parser.py
- bundlewrap/utils/cmdline.py
> move defaults for node_workers, item_workers and softlock_expiry to utils/cmdline.py

- bundlewrap/items/__init__.py
> bundlewrap.items.Item: add io.job() for running 'unless'
