- src/bundlewrap/items/users.py
Not quite sure: Is `None` appropriate here? Or should it be deleted?
> Fix: Don't crash if a user's 'groups' is None

- bundlewrap/utils/text.py
- docs/content/guide/quickstart.md
According to Unicode [0], the arcs (U256D and U2570) are "light",
whereas the vertical bar (U2503) is "heavy". This doesn't match. We
should use the light vertical bar (U2502) instead.
[0]: http://www.unicode.org/charts/PDF/U2500.pdf
> Replace U2503 with U2502

- bundlewrap/cmdline/__init__.py
- bundlewrap/node.py
- bundlewrap/utils/text.py
- bundlewrap/utils/ui.py
- docs/content/guide/env.md
- docs/mkdocs.yml
Yes, we should eliminate the underscore in `BW_IDENTITY`. I didn't want
to introduce a breaking change now, though. Having this documentation is
better than no documentation. :-)
> doc: Add documentation about environment variables

- bundlewrap/node.py
That "continue" is a gnarly beast. Before c53e863, it referred to
another, inner while-loop. That loop was remove by c53e863. This commit
re-introduces it.
This fixes #226.
> Fix `bw test`: Properly ignore DummyItems

- bundlewrap/bundle.py
- bundlewrap/cmdline/__init__.py
- bundlewrap/cmdline/apply.py
- bundlewrap/cmdline/debug.py
- bundlewrap/cmdline/run.py
- bundlewrap/cmdline/test.py
- bundlewrap/cmdline/verify.py
- bundlewrap/concurrency.py
- bundlewrap/exceptions.py
- bundlewrap/group.py
- bundlewrap/items/__init__.py
- bundlewrap/metadata.py
- bundlewrap/node.py
- bundlewrap/operations.py
- bundlewrap/repo.py
- bundlewrap/utils/__init__.py
- bundlewrap/utils/ui.py
- docs/content/guide/dev_item.md
- docs/content/repo/bundles.md
- setup.py
This went better than expected. I chose a more traditional approach than asyncio, using Python's GIL-impaired pseudo threads.
Running the same `bw test -p 4 -P 4`:
* current master: 151 seconds, ~2 GB RAM peak
* this branch: 80 seconds, 152 MB RAM peak
Even a big `bw verify` that took 559 seconds on master now completes in just 205 seconds.  
There are a few things left to do:
* handling exceptions (currently there is no way to tell which node caused an exception)
* restoring Python 2.7 compatibility using https://pypi.python.org/pypi/futures
* theres a TODO marker about hook registration that needs investigating
> Concurrency makeover

- bundlewrap/operations.py
7d90557 introduced a bug: "FOO=bar command" only works for simple
commands, but breaks when "command" is a compound command. For example:
$ bash -c 'FOO=bar echo this is okay'
this is okay
$ bash -c 'FOO=bar for i in 1 2; do echo $i; done'
bash: -c: line 0: syntax error near unexpected token `do'
bash: -c: line 0: `FOO=bar for i in 1 2; do echo $i; done'
$ bash -c 'LANG=de_DE.UTF-8 echo this is not okay; date'
this is not okay
Tue May 10 13:54:08 CEST 2016
That last one is particularly nasty because it doesn't result in an
error but simply does not use the variable (because it's unset).
Fix this by explicitly using "export".
$ bash -c 'export FOO=bar; for i in 1 2; do echo $i; done'
1
2
$ bash -c 'export LANG=de_DE.UTF-8; echo now we are fine; date'
now we are fine
Di 10. Mai 13:56:41 …
> operations.run: Fix compound commands

- bundlewrap/utils/ui.py
If stdin is not a TTY, we get this error:
error(25, 'Inappropriate ioctl for device')
This matters for operations like this:
$ yes n | bw apply -i $node
Why would I do that? To get a "diff" of the node. (Yes, we could
implement this is a new bw command, but I think the "yes" approach is
sufficient.)
> Don't flush stdin if it's not a TTY

- bundlewrap/items/users.py
The full name ("gecos") of a user might contain non-ASCII characters. On
systems with `LANG=C`, this can lead to grep saying:
Binary file matches
(Instead of the actual match.)
> Use `grep -a` for /etc/passwd on GNU

- bundlewrap/cmdline/lock.py
- bundlewrap/cmdline/parser.py
PR for #251.
Output looks like this:
$ bw lock show megasystems,super,web,bla
✓ megasystem1  no soft locks present
✓ megasystem2  no soft locks present
✓ supersystem  no soft locks present
✓ weppserver  no soft locks present
i loadbalancer  ID    Created              Expires              User                 Items  Comment  
› loadbalancer  BMYG  2016-06-10 19:19:49  2016-06-10 20:19:49  void@pinguin:master  *
i databasecluster01  ID    Created              Expires              User                 Items  Comment  
› databasecluster01  GYRX  2016-06-10 19:15:24  2016-06-10 20:15:24  void@pinguin:master  *
i mail  ID    Created              Expires              User                 Items   Comment  
› mail  GYRX  2016-06-10 19:15:24  2016-06-10 20:15:24  anna@pinguin:master  *
› mail  JUJR …
> `bw lock show` can accept multiple nodes and groups

- bundlewrap/operations.py
- docs/content/guide/installation.md
In the end, it probably does more harm than good, especially wrt BSD support.
related #241, #242
> drop requirement for bash on nodes

- bundlewrap/repo.py
PR for #263 
Runtime for `bw hash -m` remains the same, but it's now much faster for individual nodes.
> optimize execution of metadata processors

- bundlewrap/items/directories.py
File "/home/mreinhardt/py34venv/lib/python3.4/site-packages/bundlewrap/concurrency.py", line 143, in run
result = self._get_result()
File "/home/mreinhardt/py34venv/lib/python3.4/site-packages/bundlewrap/concurrency.py", line 83, in _get_result
raise exception
File "/usr/lib64/python3.4/concurrent/futures/thread.py", line 54, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/mreinhardt/py34venv/lib/python3.4/site-packages/bundlewrap/node.py", line 505, in apply
profiling=profiling,
File "/home/mreinhardt/py34venv/lib/python3.4/site-packages/bundlewrap/node.py", line 208, in apply_items
worker_pool.run()
File "/home/mreinhardt/py34venv/lib/python3.4/site-packages/bundlewrap/concurrency.py", line 152, in run
raise exc
File …
> keys.remove() now expects ValueError's instead of IndexErrors.

- bundlewrap/cmdline/verify.py
stats_summary() prints output on its own and returns nothing. This is
the error I got:
$ bw verify lulu
node health:  100.0%  (302/302 OK)
Traceback (most recent call last):
File "/home/lulu/git/bundlewrap/bundlewrap/cmdline/__init__.py", line 66, in wrapper
return f(*args, **kwargs)
File "/home/lulu/git/bundlewrap/bundlewrap/cmdline/__init__.py", line 149, in main
pargs.func(repo, text_pargs)
File "/home/lulu/git/bundlewrap/bundlewrap/cmdline/verify.py", line 109, in bw_verify
for line in stats_summary(node_stats):
TypeError: 'NoneType' object is not iterable
> Fixup for 96d3082a957bef51d31a58a2edbb9aac3dee958f

- bundlewrap/items/postgres_dbs.py
- bundlewrap/items/postgres_roles.py
- Fix crash when changing DB ownership
- Don't insist on defining passwords when a role is to be deleted
> Improve psql

- bundlewrap/items/pkg_dnf.py
- bundlewrap/items/pkg_yum.py
As described in #295 one query to the package management system should be enough to verify if packages are installed.
This PR makes use of https://github.com/bundlewrap/bundlewrap/commit/86f552b4017584b1629f4522d901c0f08fccaa05 and https://github.com/bundlewrap/bundlewrap/commit/0ad7c7303546ff4682e886b23794a412a4bd3e96 to implement this feature for dnf and yum.
Comparison:
```
before:
i ╭─────────────────┬───────┬──────┬─────┬────────┬────────╮
i │ node            │ items │ good │ bad │ health │ time   │
i ├─────────────────┼───────┼──────┼─────┼────────┼────────┤
i │ sectumsempra    │   387 │  387 │   0 │ 100.0% │ 2m 28s │
i ╰─────────────────┴───────┴──────┴─────┴────────┴────────╯
after:
i ╭─────────────────┬───────┬──────┬─────┬────────┬──────╮
i │ node            │ items │ good │ bad …
```
> cache installed packages for pkg_dnf and pkg_yum

- bundlewrap/secrets.py
- docs/content/guide/secrets.md
- tests/integration/secrets.py
> Human passwords

- bundlewrap/lock.py
> Use rm's exit code to determine return value of softlock_remove()

- bundlewrap/cmdline/items.py
- bundlewrap/cmdline/parser.py
- bundlewrap/utils/cmdline.py
This allows for exploration of item cdicts and sdicts from the CLI. That has previously only been possible for cdicts through `bw hash -d`.
> add `—state`, item and attribute args to `bw items`

- bundlewrap/node.py
Oracle Linux is actually based on RHEL. The changes are minimal and full compatibility should be given when it comes to bw.
> node.py: move oralelinux to OS_FAMILY_REDHAT

- bundlewrap/items/directories.py
> Fixup for 13e2d7e: status.sdict can be None

- bundlewrap/items/svc_systemd.py
- docs/content/items/svc_systemd.md
We often have situations where we don't want bw to start or stop a
daemon. Maybe enable it, but don't force start/stop.
> systemd: Support 'None' as value for 'running'

- bundlewrap/items/postgres_dbs.py
- docs/content/items/postgres_db.md
It's not possible to change these attributes after the DB has been created, so they're all creation-time only. :/
> postgres_db: Allow customization of encoding and collation

- bundlewrap/items/__init__.py
- bundlewrap/utils/text.py
- docs/content/repo/bundles.md
PR for #340 
still wondering if we should call it "interactive_comment" or something since "comment" is pretty generic and might be used as an item-specific attribute
> add the ‘comment’ attribute to all items

- bundlewrap/node.py
- docs/content/repo/nodes.py.md
We currently have something like this as a metadata processor. It's rather annoying to use, though, since you *always* have to check if that particular metadata is ready -- if not, bail out and try again later.
By moving this to core bw, `node.magic_number` is always guaranteed to exist and can be used right away.
(You could also interpret this as a flaw in the design of metadata processors/usage. It's a very common pattern: Check if certain metadata exists and retry later if it doesn't. Quite some amounts of boiler plate code.)
> Node magic number

- bundlewrap/items/actions.py
- bundlewrap/node.py
- bundlewrap/operations.py
- docs/content/items/action.md
- tests/integration/bw_apply_actions.py
```
actions = {
'decrypt': {
'command': 'cryptsetup --batch-mode luksOpen /dev/foo',
'data_stdin': 'my_secret_key',
},
}
```
Should the value of `data_stdin` be shown to the user? I don't think so. It could be large or binary. If we show it, we must also crop it if needed.
> Actions: Pipes

- bundlewrap/items/pkg_openbsd.py
If no packages are installed on the system, then "pkg_info" prints
nothing, i.e. an empty string. That's handled badly by split("\n"):
Python 3.6.2 (default, Jul 20 2017, 03:52:27)
[GCC 7.1.1 20170630] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "".split("\n")
['']
The following code does not expect to work on an empty string.
splitlines() handles the situation much better by returning an empty
list:
Python 3.6.2 (default, Jul 20 2017, 03:52:27)
[GCC 7.1.1 20170630] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "".splitlines()
[]
> pkg_openbsd: Fix handling of empty output from "pkg_info"

- bundlewrap/cmdline/__init__.py
For example, running "bw nodes" from a directory which is not a bw repo
would leave the cursor invisible.
> Add missing calls to io.deactivate()

- bundlewrap/cmdline/plot.py
The error was:
```
File "/Users/ayik/Repo/Python/Utils/bundlewrap/bundlewrap/cmdline/plot.py", line 32, in bw_plot_node
prepare_dependencies(node.items, node.os, node.os_version),
File "/Users/ayik/Repo/Python/Utils/bundlewrap/bundlewrap/utils/ui.py", line 359, in inner_wrapper
return wrapped_function(*args, **kwargs)
TypeError: prepare_dependencies() missing 1 required positional argument: 'node_os_version'
```
According to Contributing Doc about CAA, i think this patch is trivial / small so that i don't need to sign CAA.
> fix prepare_dependencies in bw plot

- bundlewrap/items/pkg_openbsd.py
- docs/content/items/pkg_openbsd.md
Setting "version" to select a flavor is a bit flawed because you have
to, well, select a *version*. This is not what you actually want most of
the time (at least I don't). I want to be able to select a particular
flavor and, more importantly, it shall default to the "normal" flavor if
unset.
Some examples:
pkg_add foo
Installs most recent version of package "foo". If there are
multiple flavors of that package, users will be asked
interactively to select one of them.
pkg_add foo--
Installs most recent version of package "foo" and selects the
"normal" flavor.
pkg_add foo--bar
Installs most recent version of package "foo" and selects the
"bar" flavor.
pkg_add foo-1.0.0-bar
Explicitly installs version "1.0.0" of flavor "bar".
With this patch, bw will do a "pkg_add foo--" by default. If you …
> pkg_openbsd: Support flavors

- bundlewrap/operations.py
Hi, when using custom SSH config defined in `BW_SSH_ARGS`, `scp` command may be failed since it's still using default ssh config file. This patch will make `scp` command honour `BW_SSH_ARGS`
> honour BW_SSH_ARGS for scp command

- bundlewrap/node.py
Hi, since i am using master on my dev machine, i hit a bug
```
File "/Users/ayik/Repo/Python/Iaac/bundlewrap/bundlewrap/node.py", line 278, in format_item_result
details_text = "({})".format(Item.SKIP_REASON_DESC[details])
TypeError("unhashable type: 'list'",)
vm1: unhashable type: 'list'
```
seeing other parts of the code, i think `details` kwargs should be an integer instead of a `list`. Feel free to dismiss this PR if this fix is wrong
thank you
> fix details kwarg in handle_apply_result in node.py 

- bundlewrap/items/pkg_openbsd.py
If a package is NOT installed, its flavor is unknown.
If a package IS installed, the flavor can be the empty string
(indicating the "normal" flavor) or some non-empty string (indicating
exactly that flavor). The flavor of an installed package cannot be
"None".
In other words, we must use the value of the variable "flavor" as
returned by pkg_installed(), unless the variable "version" indicates
that the package is not installed at all -- in which case "flavor" will
be set to "None" which we must substitute by _("none").
This patch fixes a regression in bw 3.2.0: bw would always report
packages as "installed as the wrong flavor" if "pkg_info" didn't show a
flavor for a package.
> pkg_openbsd: Only use "none" in sdict if not installed

- bundlewrap/items/postgres_dbs.py
- bundlewrap/items/postgres_roles.py
Assigning postgres_* items to a node and then running "bw verify $node"
results in some RemoteExceptions. That's because we try to run "sudo
postgres ...", but the user "postgres" does not yet exist. Usually,
bundles will have dependencies for that (install pkg_apt:postgresql
before creating any databases), but "bw verify" ignores dependencies.
So, allow these ".run()" calls to fail. This makes "bw verify" report
items as failed -- this is what we want.
> postgres_*: No longer throw exceptions

- docs/content/repo/nodes.py.md
The code which is shown in the documentation for searching a nodes folder for nodes files is not path independent. If you try to use this code with an script it does not work as expected, since it does not find its nodes files.
This patch adds the repo path to the mix, which fixes the problem. Additionaly it adds the os.path.join method, which makes this code run on windows as well.
> made code in docu path independent

- bundlewrap/items/kubernetes.py
"Older" versions of Python (< 3.6?) appear to need this, while Python 3.7 is fine:
```
Python 3.7.0 (default, Jul 15 2018, 10:44:58) 
[GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from json import loads
>>> loads(b'{}')
{}
>>> loads('{}')
{}
```
> KubernetesItem: .decode() the output of kubectl

- bundlewrap/utils/remote.py
As the end of the output of `file -bh` is "user controlled" for symlinks, the beginning of the string should be used to avoid problems.
In my case, this bug was triggered when creating a vhost configuration for FusionDirectory.
> Fix an edge case when trying to create a symlink that ends with 'directory'

- bundlewrap/utils/__init__.py
- docs/content/guide/api.md
- tests/integration/secrets.py
We have *a lot* of these in our k8s stuff:
```python
k8s_secrets = {
'foo': {
'context': {
'username': b64encode(str(teamvault.username('1234')).encode('UTF-8')).decode('UTF-8'),
},
'manifest_file': 'foo.yaml',
'manifest_processor': 'mako',
},
}
```
That's wrong because Faults will get resolved too early … so, that b64encode dance must be done in the template. That's pretty noisy and a little annoying. :)
With this PR, you can do the following and be done with it:
```python
k8s_secrets = {
'foo': {
'context': {
'username': teamvault.username('1234').b64encode(),
},
'manifest_file': 'foo.yaml',
'manifest_processor': 'mako',
},
}
```
> Fault: Support .b64encode()

- bundlewrap/utils/__init__.py
Fixes issues with nested Faults of different nesting levels. For
example:
from bundlewrap.utils import Fault
def wrap(something):
def callback():
return something
return Fault(callback)
foo_level1 = wrap('foo')
bar_level1 = wrap('bar')
bar_level2 = wrap(bar_level1)
res = foo_level1 + bar_level2
print(res)
Resulted in the following Exception:
TypeError: can only concatenate str (not "Fault") to str
> Fault: Resolve recursively

- bundlewrap/utils/__init__.py
You can't sort a list of Faults in templates without this.
> Fault: Implement __lt__

- bundlewrap/secrets.py
- docs/content/guide/secrets.md
- tests/integration/secrets.py
For when you just need some random bytes that are derived from an
identifier.
Faults are expected to wrap other Faults or 'str', but not plain bytes,
so we always have to b64encode our data.
> Add repo.vault.random_bytes_as_base64_for()

- bundlewrap/items/__init__.py
For example, an action's "unless" command can now contain a Fault.
> items: Allow Faults in builtin attributes

- bundlewrap/metadata.py
- bundlewrap/repo.py
- docs/content/repo/metadata.py.md
- tests/integration/bw_metadata.py
This is illegal because it can result in duplicate metadata, like
merging lists in merge_dict().
> Metaprocs: Detect when users return an original metadata object with an invalid flag

- bundlewrap/items/kubernetes.py
This PR fixes a KeyError that occurs when triggering the duplicate definition BundleError in the kubernetes item.
``` 
File "/usr/local/lib/python3.7/site-packages/bundlewrap/items/kubernetes.py", line 246, in _check_bundle_collisions
bundle2=item.bundle.name,
KeyError: 'node'
```
> Fix KeyError in kubernetes item

- bundlewrap/cmdline/diff.py
Our input to unified_diff() does not have line terminators. We must set
this flag to tell unified_diff() about that.
> bw diff: Fix empty lines

- bundlewrap/cmdline/__init__.py
- bundlewrap/repo.py
- docs/content/guide/api.md
This allows you to call "r = Repository('.')" in scripts. Before, you
had to duplicate the root detection in your own code or you had to rely
on using $BW_REPO_PATH.
"Repository()" still yields a repo in /dev/null.
> Move repo root detection to constructor of Repository

- bundlewrap/repo.py
Items can now be logically seperated inside items/.
Especially helpful for writing and maintaining custom plugins,
which bring items with them.
> Find Items recursively

- bundlewrap/items/kubernetes.py
- docs/content/guide/kubernetes.md
- docs/content/items/k8s.md
CC #488.
Providing a default is meaningless, if we don't also validate that the
objects actually comply with that version.
> k8s_*: No longer provide default for apiVersion

- docs/content/misc/contributing.md
Explicitly include the trailing slash in this example to indicate that
we're talking about the directory (instead of some abstract "goal" or
something like that).
> docs: "py.test" needs an argument

- bundlewrap/metadata.py
- bundlewrap/utils/dicts.py
- bundlewrap/utils/metastack.py
- tests/unit/metastack.py
- tests/unit/utils_dicts.py
> bring back deepcopy_metadata to replace freeze_object

- bundlewrap/secrets.py
- bundlewrap/utils/__init__.py
- docs/content/repo/metadata.py.md
- tests/integration/secret.py
- tests/unit/faults.py
I am not happy with this. It is better than before, but it is very easy to accidentally create collisions, thus making unequal Faults “equal”. It’s just not a fool proof interface.
But how else would you make Faults comparable?
> [RFC] Faults get identifiers to be comparable

- bundlewrap/cmdline/nodes.py
- bundlewrap/group.py
- bundlewrap/metadata.py
- bundlewrap/node.py
- bundlewrap/repo.py
- bundlewrap/utils/dicts.py
- bundlewrap/utils/plot.py
- bundlewrap/utils/text.py
- docs/content/guide/toml.md
- docs/content/index.md
- docs/content/repo/nodes.py.md
- docs/mkdocs.yml
- setup.py
```$ bw debug -n pi-cabinet
BundleWrap 4.0.0 interactive repository inspector
> You can access the current repository as 'repo'.
> You can access the selected node as 'node'.
>>> node.file_path
'[...]/nodes.py'
>>> node.toml
[...]
ValueError: node pi-cabinet not in TOML format
>>> node.toml_save()
>>> node.file_path
'[...]/nodes/pi-cabinet.toml'
>>> node.toml
{'hostname': '[...]', 'bundles': ['led-cabinet', 'led-neopixel'], 'metadata': {'ubuntu_release': 'bionic', 'interfaces': {'eth0': {'dhcp': True, 'ip_addresses': ['192.168.36.3']}}, 'systemd': {'persistent_journal': False}}}
>>> node.toml_set("metadata/some/thing/nested", 47)
>>> node.toml_save()
$ cat nodes/pi-cabinet.toml
hostname = "[...]"
bundles = ["led-cabinet", "led-neopixel"]
[metadata]
ubuntu_release = "bionic" …
```
> add toml nodes and groups

- bundlewrap/cmdline/parser.py
Wasn't immediately clear what was going on with uncolored output.
> "bw metadata": Explain uncolored output

- bundlewrap/items/git_deploy.py
HTTP does not support that.
Port of https://github.com/bundlewrap/plugins/pull/11.
> git_deploy: Do not use shallow clones for HTTP

- docs/content/repo/groups.py.md
- docs/content/repo/metadata.py.md
- docs/content/repo/nodes.py.md
This should be documented explicitly, since it's a bit confusing (reactors can react to static metadata, but they can't overwrite it, only maybe merge into it).
> Explicitly document metadata priority

- bundlewrap/metadata.py
Makes it possible to return identicals 'defaults' from different bundles
or do more complicated stuff like this:
@metadata_reactor
def generic_default(metadata):
def_iface = list(metadata.get('interfaces').keys())[0]
return {
'internal_interface': metadata.get('internal_interface', def_iface),
}
@metadata_reactor
def corner_case(metadata):
special_iface = 'eth2'
if metadata.get(f'interfaces/{special_iface}', None) is not None:
return {
'internal_interface': special_iface,
}
else:
return {}
> Metadata: Only report clashes if values are not equal

- bundlewrap/utils/metastack.py
The old code returned UNMERGEABLE values if they showed up in lower
layers. See failed tests.
> Metastack: Only return early if this is the first value we see

- bundlewrap/utils/metastack.py
For reasons beyond my understanding, this caused segfaults on our build
agent with Ubuntu's Python 3.8.0. Doesn't happen on my local machine
with Arch Linux's Python 3.8.3.
> Avoid Python segfaults

- bundlewrap/utils/remote.py
file(1) began classifying JSON files as "JSON data" in some recent
release.
> Add "JSON data" to text types

- bundlewrap/metadata.py
If you put floats in there, it just said "illegal value: 20.04" and
nobody understood why.
> Make message about illegal metadata more helpful

- bundlewrap/utils/__init__.py
- tests/unit/faults.py
Mutable objects are not hashable in Python. We'd like to pass those as
arguments to Faults, though. For example:
def whatever(data):
return json.dumps(data)
f = Fault('foo', whatever, data={'what': 'ever', 'some': other_fault})
Mutable objects are not hashable, because, well, they're mutable. You
cannot determine a hash, because that object might change later
in-place.
Strictly speaking, this is a problem for us, too:
def my_function(data):
return f'{repr(data)}'
dirty_dict = {
'foo': 0,
}
f = Fault('whatever', my_function, data=dirty_dict)
dirty_dict['foo'] = 1
g = Fault('whatever', my_function, data=dirty_dict)
print(f'Will print False: {f == g}')
print(f'Will print same string twice, which is wrong: {str(f)}, {str(g)}')
Let's discuss whether we should do deepcopy kwargs or not.
> Fault: Hash kwargs recursively

- bundlewrap/items/git_deploy.py
- docs/content/guide/env.md
- docs/content/items/git_deploy.md
Goals:
* Per-process cache: A single instance of `bw` (e.g., `bw test -d 3`) shall not clone repos over and over again.
* Shared cache (user opt-in): Multiple instances of `bw` shall be able to use a shared cache, if configured.
* Backwards-compatible. (I haven’t spent time on trying to improve the repo map.)
> git deploy cache

- docs/content/guide/api.md
Without dashes, all this gets mangled into one large paragraph.
> docs: Add missing dashes to guide/api.md

- docs/content/guide/dev_item.md
The attribute of ItemStatus is called keys_to_fix instead of keys. This is fixed in the example item comment.
> fix typo in docs

- bundlewrap/group.py
- bundlewrap/lock.py
- docs/content/repo/nodes.py.md
Add the `lock_dir` property that dictates where locks are stored on a
specific node. The peviously hardcoded `/var/lib/bundlewrap` is used as
a default. With this change, bundlewrap can be used on nodes, where
/var/lib is not acessable for some reason (e.g. mounted readonly).
This change also allows for usage on nodes without root access (#542)
I tested this manually using bw lock and bw apply. If you want an automated test, let me know!
Also I'm unsure if this change qualifies as IP.
> allow lock dir to be configured per node

- bundlewrap/group.py
- bundlewrap/items/pkg_pip.py
- docs/content/repo/nodes.py.md
This allows to customize the call to `pip` in `pkg_pip:` items to fix the issue discussed in #524.
I thought about changing the default to pip3, but that may break existing repos, so i've decided against that.
> items/pkg_pip: allow configuring pip_command

- bundlewrap/cmdline/apply.py
When setting the progress total by using count_items() before calling
the `apply_start` hook, all bundles and items will be parsed. That might
be undesirable if a hook should make changes to the local state that
would reflect in an item's state. Therefore we should set the progress
after calling the apply_start hook.
This change is backwards compatible because if a hook actually acesses
some of the bundles/items in the repo, they will be dynamically parsed
on demand thanks to the use of @cached_property.
> hooks: call apply_start before parsing items

- bundlewrap/utils/ui.py
1000 short lines still call for running a pager.
Either this, or *always* pipe to `less` and ask users to set `-F` in their `$LESS` if they want the `--quit-if-one-screen` behaviour. The latter is what I originally meant in #551, but it’s probably not going to happen, since BSD’s `less` is so broken.
> Pipe to 'less' if there are too many lines

- bundlewrap/cmdline/test.py
Metadata is only calculated once now and then we check if metadata or
cdicts have changed.
Before:
$ time bw test -d 2 -m 2 my.dns.server
✓ Metadata remained the same after being generated 2 times
✓ Configuration remained the same after being generated 2 times
real    0m48.516s
user    0m47.252s
sys     0m1.251s
After:
$ time bw test -d 2 -m 2 my.dns.server
✓ Configuration remained the same after being generated 2 times
✓ Metadata remained the same after being generated 2 times
real    0m35.822s
user    0m34.920s
sys     0m0.914s
> bw test: Merge "-d" and "-m"

- bundlewrap/utils/__init__.py
- docs/content/guide/api.md
This will allow users to easily generate htpasswd-compatible `username:password` lines. Similar functionality is already present in trehn/bundlewrap-teamvault for teamvault entries.
This pull request will fix #578
> bundlewrap.utils.Fault: add .as_htpasswd_entry()

- bundlewrap/items/pkg_freebsd.py
- bundlewrap/items/users.py
- docs/content/items/pkg_freebsd.md
- docs/content/repo/items.py.md
- docs/mkdocs.yml
- tests/unit/pkg_freebsd.py
Manages packages via `pkg` on FreeBSD installations. Basically a copy of pkg_openbsd which I adapted to FreeBSD.
I tested it with a spare FreeBSD machine, should work as advertised.
I'm not particularly into Python and/or bundlewrap, so code style comments etc. are much appreciated :-)
> FreeBSDPkg: Initial implemenation

- bundlewrap/items/users.py
FreeBSD's user management is slightly different from the other OSes, this PR fixes this.
It's ad-hoc and (IMO) pretty ugly, but I believe the added complexity of refactoring the argument
dictionary to be OS-specific is too high (for now).
Any comments appreciated!
> User: Fix for FreeBSD

- bundlewrap/repo.py
Do as the comment says and abort if the directory is not empty.
CC #530 
Note that both the old and the new code has a race condition. If two processes try to do this at the same time, weird things will happen. I can only see one clean solution to this: Stop requiring that the directory already exists. Then we can do an `mkdir()` and the one process where this succeeds wins and creates a consistent new repo. Same idea as with directory-based locks in the file system.
That race condition is probably pretty rare, though, and I’m not sure if fixing it is worth breaking the API.
> bw repo create: Do not clobber existing repos

- AUTHORS
- bundlewrap/items/svc_systemd.py
- docs/content/items/svc_systemd.md
I want to propose adding the possibility to (un)mask systemd units via a new attribute `masked` (defaults to `False`) on `svc_systemd`. Inspired e.g. by Ansible [providing it as well](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#parameter-masked). I'd happy if you consider my contribution.
I manually tested this successfully on Debian 10 (Buster) where:
```
$ systemctl --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```
I have to admit that I did not add a integration (or unit) test for this feature as I saw that no `svc_*` is tested.
> Add svc systemd masked attribute

- bundlewrap/items/actions.py
- docs/content/items/action.md
- tests/integration/bw_apply_actions.py
I propose allowing to pass in a list of integers to the `expected_return_code` attribute of an `action` in addition to passing in a single integer. The meaning here is that any of the listed integers signifies a successful execution of the action's `command`.
One use case I have is running `apt-get update` which may either exit with `0` (package lists got updated) or `100` (another process held the lock on the package lists) - in my setup I'd be fine with both as I just want to at least try to update the package lists once on a run. Currently I have to ignore the exit code alltogether on that aciton.
Maybe similiar use cases exist as well, where you want to allow certain exit codes without ignoring all of them.
I also added some tests for the `expected_return_code` attribute in general …
> Allow checking `action`s against multiple expected return codes

- tests/integration/bw_apply_git_deploy.py
I saw that https://github.com/bundlewrap/bundlewrap was adjusted to use `main` branch instead of `master` in the last 1-2 days. As this branch name is relied on in tests of `git_deploy` item, they were failing. This simple PR proposes to fix this.
> Fix tests to use new repo branch name main

- .gitignore
- AUTHORS
- bundlewrap/items/pkg_apk.py
- bundlewrap/items/svc_openrc.py
- bundlewrap/node.py
- docs/content/items/pkg_apk.md
- docs/content/items/svc_openrc.md
- docs/mkdocs.yml
This patchset implements Alpine Linux support to bundlewrap by adding two new items:
- `pkg_apk`: Item for interacting with Alpine's `apk` package manager. Currently supports installing and uninstalling packages.
- `svc_openrc`: Item for managing services using Alpine's default init system, `OpenRC`. Supports (re)starting, reloading, stopping, and enabling/disabling services.
I haven't written any tests since there doesn't seem to be a system in place for testing OS-specific features, but I'm happy to add those if anyone has a suggestion on how to do that.
> Add support for Alpine Linux

- .github/workflows/tests.yml
Reduces CI runtime on GHA from ~10minutes ([old run](https://github.com/bundlewrap/bundlewrap/actions/runs/580929111)) to ~3minutes, providing faster feedback and avoids wasting resources.
**Note:** this PR also adjusts the GHA workflow to use `main` branch name!
> Speedup CI by using SSH multiplexing on localhost

- bundlewrap/items/pkg_opkg.py
As `OpkgPkg` is derived from `Pkg` which already defines `block_concurrent()` in [a generic way](https://github.com/bundlewrap/bundlewrap/blob/main/bundlewrap/items/pkg.py#L18-L20), the re-definition with same functionality in `OpkgPkg` can be removed.
> Remove redundant block_concurrent() from pkg_opkg, is already defined in Pkg

- bundlewrap/items/git_deploy.py
This nuked the entire existing env, including variables like
SSH_AGENT_PID, which made Git ask for credentials -- which it can't.
This was broken only recently: https://github.com/bundlewrap/bundlewrap/commit/00b58e28c6b80c1494286377dc1387cf17bedc49#diff-a51d0a8a02830180a5762cfc57e50c2e75e9e57b6d16356d4655c1e555cf3019R215
> Fix git_deploy: Do not clobber existing environment

- bundlewrap/group.py
- bundlewrap/items/postgres_dbs.py
- bundlewrap/items/postgres_roles.py
- bundlewrap/node.py
- bundlewrap/operations.py
- docs/content/items/postgres_db.md
- docs/content/items/postgres_role.md
This patch adds a new group/node attribute called `run_as_command`, which specifies the command that should be used to run commands as another user. This defaults to `sudo -u {user} {command}` but can easily be changed to allow other privilege escalators, for example: `doas -u {user} {command}`. This functionality is wrapped in a new Node method, `node.run_as(user, command, ...)`.
The postgres items have been updated to use the new `run_as` method, as well as using psql's `-c` argument rather than piping SQL directly into psql, as this makes it easier to run under the correct user.
Also updated the Postgres docs to include the `delete` attribute, which seems to be missing.
Fixes #612
> Don't rely on sudo to run postgres items

- bundlewrap/items/groups.py
- bundlewrap/items/users.py
On GNU (and probably FreeBSD), the order doesn't matter.
On OpenBSD, creating or modifying users was broken.
-----
This was probably broken since 3f9bdf8fd749d4cba6ffc69fa3c562b6d80d68ce, I’m not sure. I don’t have a FreeBSD box ready, so it would be great, if you, @ThreeFx, could give this PR a spin and see if creating users still works on FreeBSD. Thanks!
> Users: Username must come last

- bundlewrap/items/files.py
-   Scientific notation is not compatible with sort(1), so just print
everything as plain floats.
-   If the "s" is put directly after the number, you can't just use
something like `awk '/rendered in/ { print $4 }' | sort -n`, but
you have to take an extra step to separate the number and the "s".
> Make "rendered in" lines easier to work with

- docs/content/items/file.md
> file: clarify the behaviour of `None` for owner, mode and group

- bundlewrap/utils/ui.py
strftime() is expensive and isoformat() shows almost the same
information, the difference being that annoying "T" from ISO8601.
For large log output (couple of hundred MB), this can shave off a few
billion CPU cycles. It's not a lot, but it's something.
> Use isoformat() in debug log

- bundlewrap/utils/text.py
- bundlewrap/utils/ui.py
- tests/unit/utils_text.py
On narrow terminals, the status line showing the current job was being
cut off, because we counted escape sequences as visible characters.
> Fix "job" lines being cut off too early

- bundlewrap/metadata.py
Currently, metadata like
```
{
'foo': {
('a', 'b'),
('c', 'd'),
}
}
```
is not possible, because tuples are converted to lists in deepcopy_metadata(). As lists are not hashable, we can not have sets of tuples. This PR makes deepcopy_metadata() preserve tuples.
> Sets of tuples 1/2: deepcopy_metadata() preserves tuples

- bundlewrap/metadata.py
This change serves two purposes:
- simpler code
- original type of objects is preserved, whatever it was
As a side effect of preserving the types, you can now use custom types to work around some limitations:
You can now, for example, implement a hashable dict and use sets of dicts in metadata like:
```
'set': {
hdict({
'a': 1,
'b': {
'c': 3,
},
}),
hdict({
'a': 2,
'b': {
'c': 4,
},
}),
},
```
(https://github.com/CroneKorkN/bw-example-hdict/blob/main/nodes.py)
This is useful when mapping configurations of applications to metadata, where you have no control of the structure and need some kind of list with dicts in them.
> Sets of tuples 2/2: refactor deepcopy_metadata()

- bundlewrap/items/pkg_pip.py
A couple of items allow multiple runs in parallel. This might work if you're installing multiple *different* packages, but what if those package pull in the *same* dependencies? I can't imagine that that's healthy. 🤔
This PR only changes `pkg_pip`, but there's more. Let's discuss first, though.
> Do more package items need "block concurrent runs"?

- bundlewrap/operations.py
Otherwise, scp will interpret everything after the first : as file path,
thus connecting to the host will fail.
This fixes #689
> operations.upload(): enclose hostname in [] if it's an ipv6 address

- .github/workflows/tests.yml
- bundlewrap/repo.py
- bundlewrap/utils/dicts.py
- setup.py
tomlkit has performance issues.
untoml() has been removed, because it was not part of the official API
documented here: https://docs.bundlewrap.org/guide/api/#reference
> Use rtoml for normal loading

- AUTHORS
- bundlewrap/items/pkg_apt.py
Currently, there is no way to remove essential packages. This change allows to do so by executing all purges with --allow-remove-essential.
> Allow removal of essentials with pkg_apt

- bundlewrap/cmdline/items.py
a) It fails, b) there is nothing to preview as these are no templates (just like "binary" files).
This was the original error:
```
Traceback (most recent call last):
File "/home/user/.local/lib/python3.10/site-packages/bundlewrap/utils/cmdline.py", line 69, in wrapper
return f(*args, **kwargs)
File "/home/user/.local/lib/python3.10/site-packages/bundlewrap/cmdline/__init__.py", line 77, in main
pargs.func(repo, text_pargs)
File "/home/user/.local/lib/python3.10/site-packages/bundlewrap/cmdline/items.py", line 63, in bw_items
write_preview(item, args['file_preview_path'])
File "/home/user/.local/lib/python3.10/site-packages/bundlewrap/cmdline/items.py", line 21, in write_preview
content = file_item.content
File "/home/user/.local/lib/python3.10/site-packages/bundlewrap/utils/__init__.py", …
```
> "bw items -w" should not try to preview downloads

- bundlewrap/items/routeros.py
We *think* we saw this:
-   We bombarded a switch with 64 requests at once.
-   The switch took more than 10 seconds to respond for one of those
requests. This triggers librouteros's timeout during recv().
-   Data for that request might still arrive later on the socket, so one
of the next invocations of rawCmd() gets a completely unrelated
answer.
> routeros: Drop connections on errors

- bundlewrap/items/svc_systemd.py
I don't know where the string "runtime-enabled" comes from. It has been called "enabled-runtime" in their manpage since at least 2013.
"runtime-enabled" worked on Ubuntu 18.04, but that's the only reference to it that I can find. It no longer does on Ubuntu 22.04, though.
> svc_systemd: Fix svc_enabled()

- bundlewrap/node.py
- bundlewrap/operations.py
For example: Applying a node with `username` overridden node fails because the `scp` runs *with* the desired `username`, but the following `mv` (which uses a path *relative* to the user’s home) runs *without* `username`.
If this never showed up before, I’m probably the first person to use this feature? 🥴
> SSH argument "username" missing in some places

- bundlewrap/deps.py
If an item type provides canned actions, item.__deps contained dependencies to those canned actions right from the start. This meant that this construct always returned an empty list ("not item.__deps" was never true):
list(filter(
lambda item: not item.__deps and item not in processed_items,
type_items,
))
As a result, concurrency blockers were never inserted for such item types.
Should also fix #554.
> Fix block_concurrent() not working if item provides canned actions

- bundlewrap/items/git_deploy.py
Not very relevant for performance here, but preexec_fn is about to be deprecated, so let's just remove it while we're at it.
https://github.com/python/cpython/issues/82616
> git_deploy: Stop using preexec_fn

- tests/integration/bw_apply_actions.py
- tests/integration/bw_apply_autoonly.py
- tests/integration/bw_apply_directories.py
- tests/integration/bw_apply_files.py
- tests/integration/bw_apply_precedes.py
- tests/integration/bw_apply_secrets.py
- tests/integration/bw_hash.py
- tests/integration/bw_metadata.py
- tests/integration/bw_stats.py
- tests/integration/bw_test.py
Note that the tests in bw_apply_actions.py were mostly without effect.
Maybe we should discuss moving this to `run()` itself because it is easy to forget to perform this check. It is a useful check, though, as it can reveal all kinds of unexpected failures.
> Integration tests: Always check returncode of run()

- bundlewrap/deps.py
This is a quick win, we can easily get rid of the quadratic runtime here.
-   In a repo with one node that has 2000 file items, the runtime of `bw test node-1` drops from ~8.4 seconds to ~4.7 seconds.
-   The “processing dependencies” stage of our Icinga node drops from ~32 seconds to ~21 seconds.
> deps: Optimize _add_incoming_needs()

- bundlewrap/cmdline/pw.py
- bundlewrap/secrets.py
- tests/integration/bw_pw.py
Encrypting always worked. With this patch, decrypting does, too:
```
$ dd if=/dev/urandom of=myfile bs=1M count=1 && md5sum myfile && bw pw -e -f myfile.vault myfile && rm myfile && bw pw -d -f myfile myfile.vault && md5sum myfile
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00501153 s, 209 MB/s
191b44f97abe8901b002b52865e2ba9c  myfile
191b44f97abe8901b002b52865e2ba9c  myfile
```
To be honest, it feels a bit like a hack, though. The content is wrapped in a `Fault` and it doesn’t look like that class is supposed to deal with `bytes`, is it? 🤔
> bw pw -f: Allow for binary files

- bundlewrap/operations.py
The events arrive a little bit different than on GNU. Looks like macOS keeps the POLLIN flag even on EOF, meaning we never processed the POLLHUP and thus never closed the fd. The result was an infinite loop, bw was stuck at "establishing connection to ...".
> Fix poll() on macOS

- bundlewrap/items/files.py
- bundlewrap/utils/__init__.py
- docs/content/items/file.md
- setup.py
addresses #749 and replaces #748
This will add a global default download timeout of 60s. Not having a timeout there before is problematic enough that I don't care about backwards compatibility here. I doubt anyone relies on bw blocking forever. If for some reason a downloaded file needs a longer timeout (because it takes time to generate it server-side for example), this can now be addressed at item level with the new `download_timeout` attribute.
Also if `content_hash` is not set for a download file item, the URL will only be checked with a HEAD request instead of downloading the complete file just to throw it away.
> Timeouts and HEAD requests for file downloads

- bundlewrap/items/files.py
Showing the node name and the file path seemed to be the correct thing initially, however i've found that showing that info is often not what users expect.
Showing the actual url that's being downloaded is much more intuitive to users. Especially inexperienced bw users have contacted me and asked why bundlewrap was downloading a file from the node when it should be *uploading* that file instead.
> items/files: show url instead of nodename+path when downloading file

- bundlewrap/cmdline/lock.py
This used to crash if there were no targets whatsoever:
$ bw lock add foo -e 1m -c test
» foo  is a dummy node
Traceback (most recent call last):
File "/home/user/git/bundlewrap/bundlewrap/utils/cmdline.py", line 71, in wrapper
return f(*args, **kwargs)
^^^^^^^^^^^^^^^^^^
File "/home/user/git/bundlewrap/bundlewrap/cmdline/__init__.py", line 77, in main
pargs.func(repo, text_pargs)
File "/home/user/git/bundlewrap/bundlewrap/cmdline/lock.py", line 44, in bw_lock_add
max_node_name_length = max([len(node.name) for node in target_nodes])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
> bw lock: Don't do anything if there are no targets

- bundlewrap/cmdline/metadata.py
- bundlewrap/cmdline/parser.py
- bundlewrap/metadata.py
- bundlewrap/utils/__init__.py
- tests/integration/bw_metadata.py
This implements https://github.com/bundlewrap/bundlewrap/issues/557.
> `bw metadata`: Don’t resolve Faults by default

- bundlewrap/secrets.py
Feels like we should have that when implementing #758, so we atleast have some idea what the secret is about.
I have decided to not include the "to decrypt" text in `decrypt()`, because strings might be rather long.
> SecretProxy: show identifier of genereated secrets

- bundlewrap/items/pkg_pip.py
- docs/content/items/pkg_pip.md
Adding `--break-system-packages` should be relatively uncontroversial.
Switching from `pip freeze` to `pip list` is somewhat necessary in order to make good use of `--break-system-packages` and to transition away from pip packages (see commit message). I am not sure about compatibility, though. I tested it on:
-   OpenBSD 7.5 (pip 24.0 on Python 3.10)
-   Current Arch (pip 24.0 on Python 3.12)
-   Ubuntu 20.04 (pip 20.0.2 on Python 3.8)
-   Ubuntu 22.04 (pip 22.0.2 on Python 3.10)
-   Ubuntu 24.04 (pip 24.0 on Python 3.12)
Notably: *Not* tested on Ubuntu 18.04. If we care about that version, I’ll set up a VM.
> Address two pip issues

- bundlewrap/items/pkg_pip.py
> Fix pkg_pip: Ignore case of package names

- bundlewrap/items/postgres_roles.py
**Problem:**
postgres_role did not accept scram sha 256, because it used CREATE and ALTER, which does not accept anything other than md5 as hash. When passing postgres a password that starts with "md5" it thinks that it is not a password but instead a hash. Anything other that does not start with "md5", postgres trys to hash it.
**Solution:**
Splitted the function so we have one for creating the user and one for setting the password hash directly.
> Items postgres role support modern algorithms

- bundlewrap/items/directories.py
A directory item wants a certain directory to exist. It does not mean that this directory must be *empty*. There is no need for recursion.
> directory: Do not use "rm -rf"

- bundlewrap/items/pkg_dnf.py
-d and -e are both deprecated[1]
"dnf list --installed" is compatible with both dnf versions
[1] https://dnf.readthedocs.io/en/latest/command_ref.html
#786
> pkg_dnf: adjustments for dnf5 compatibility

- bundlewrap/items/pkg_dnf.py
This lead to a spurious package called "Installed" to be added to the list.
> pkg_dnf: Skip header when listing all packages

- bundlewrap/cmdline/parser.py
- bundlewrap/cmdline/plot.py
- bundlewrap/deps.py
- bundlewrap/itemqueue.py
- bundlewrap/node.py
- bundlewrap/utils/plot.py
Before polishing this further, I’d like to get some feedback.
We saw in #779 that injecting concurrency blockers can lead to (artificial, unintended) loops. This PR addresses that issue by getting rid of concurrency blockers altogether.
Instead, `Node::apply_items()` now keeps track of which item types are currently running. When asking for the next available item to apply, only non-conflicting items will be considered.
> Remove concurrency blockers, `ItemQueue` handles this now

- bundlewrap/cmdline/debug.py
It was really annoying to create https://github.com/bundlewrap/bundlewrap/pull/732 without history
> `bw debug`: add history reading and saving

- bundlewrap/cmdline/__init__.py
- bundlewrap/cmdline/generate_completions.py
- bundlewrap/cmdline/parser.py
The idea is to generate the possible targets asynchron and store them to a file to speed up the completion itself.
This PR contains (so far) only the changes needed in the bundlewrap parser for the completion.
Maybe we could also integrate a script/option to generate this file, but I am not sure about an good "location" for this.
Also documentation containing the dependency to argcomplete and its configuration is missing yet.
Feel free to share your thoughts and suggestions :)
> Add bash completion for targets via argcomplete

- bundlewrap/cmdline/lock.py
- bundlewrap/cmdline/parser.py
- bundlewrap/lock.py
This PR adds a new flag to `bw lock show`, allowing to hide empty lines of nodes which don't have any locks.
> bw lock show: add quiet mode

- bundlewrap/utils/cmdline.py
I broke this here: https://github.com/bundlewrap/bundlewrap/pull/808/files#diff-877d04f8faf13b17b13c7dac7cbac14ce62fcbb69a75ea7ad6f05c53be07570cR147-R149
fixes #822 822
> utils.cmdline: fix trailing comma for HELP_ vars

- bundlewrap/cmdline/generate_completions.py
- bundlewrap/cmdline/parser.py
- bundlewrap/utils/text.py
For shell completions in scripts or other tools you might need only nodes or groups as completion.
This allows to differentiate between nodes and groups in the generated target file.
> cmdline/parser,generate_completions: Add prefix for nodes and groups

- bundlewrap/cmdline/generate_completions.py
- bundlewrap/cmdline/parser.py
fixes #833 
* 1cf11c5e - move `bw generate-completions` to correct position in parser - Franziska Kunsmann
* 286b5403 - rename `bw generate_completions` to `generate-completions` - Franziska Kunsmann
* 7c4b0607 - cmdline.generate_completions: ensure file is sorted - Franziska Kunsmann
> shell completion fixups

- bundlewrap/items/routeros.py
Setting items with an explicit `dynamic=no` filter worked as intended when the ressources already exist, but when new ones were created the `dynamic=no` flag was also being set, which resulted in error messages as it's not a configurable option.
An example on where this might fail:
```
routeros[f"/interface/bridge/vlan?vlan-ids={conf['id']}&dynamic=no"] = {
'bridge': 'bridge',
'untagged': sorted(conf['untagged']),
'tagged': sorted(conf['tagged']),
[...]
}
```
The filter is necessary so bundlewrap doesn't try to update dynamic ressources on the system, but at the same time it results in an error when ressources didn't previously exist.
This pull-requests just filters out the `dynamic` keyword from the options sent to the API during creation of new ressources.
Afaik there are no cases where …
> routeros: ignore 'dynamic' keyword during creation of new ressources

- bundlewrap/items/files.py
Suppose a URL responds with something like HTTP 301. That is enough to satisfy `raise_for_status()`. But this doesn't check whether the resource *after* the redirect actually exists. This can result in successful runs of `bw test` and then `bw apply` fails.
Closes #835.
> files: Follow redirects in `check_download()`
